name: isolate_flutter
description: IsolateFlutter provides a way to launch 'dart:isolate' library in Flutter (iOS and Android).
version: 3.0.1
homepage: https://github.com/thongdn-it/isolate_flutter/tree/master/isolate_flutter
repository: https://github.com/thongdn-it/isolate_flutter/tree/master/isolate_flutter

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
